apiVersion: v1
kind: ReplicationController
metadata:
  name: gitlab
  labels:
    name: gitlab
spec:
  replicas: 1
  selector:
    name: gitlab
  template:
    metadata:
      labels:
        name: gitlab
    spec:
      nodeSelector:
        servertype: worker
      containers:
      - name: gitlab
        limits:
          memory: "1000Mi"
        image: sameersbn/gitlab:8.0.2
        volumeMounts:
        - mountPath: /home/git/data
          name: gitlab-data
        ports:
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22
        env:
          - name: TZ
            value: Europe/Ljubljana
          - name: SMTP_ENABLED
            value: "true"
          - name: SMTP_DOMAIN
            value: gatehub.net
          - name: SMTP_HOST
            value: smtp.gmail.com
          - name: SMTP_PORT
            value: "587"
          - name: SMTP_USER
            value: janz@gatehub.net
          - name: SMTP_PASS
            value: <pass>
          - name: SMTP_STARTTLS
            value: "true"
          - name: SMTP_AUTHENTICATION
            value: login
          - name: GITLAB_TIMEZONE
            value: Ljubljana
          - name: GITLAB_HOST
            value: gitlab.default.kubernetes.io
          - name: GITLAB_PORT
            value: "80"
          - name: GITLAB_SSH_PORT
            value: "22"
          - name: GITLAB_EMAIL
            value: test@email.com
          - name: GITLAB_EMAIL_REPLY_TO
            value: test@gmail.com
          - name: GITLAB_BACKUPS
            value: daily
          - name: GITLAB_BACKUP_TIME
            value: "13:20"
          - name: DB_HOST
            value: localhost
          - name: DB_TYPE
            value: postgres
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: gitlab
          - name: DB_USER
            value: gitlab
          - name: DB_PASS
            value: <dbpass>
          - name: REDIS_HOST
            value: localhost
          - name: REDIS_PORT
            value: "6379"
          - name: GITLAB_SECRETS_DB_KEY_BASE
            value: <secret_db_key_base>
      - name: gitlab-postgres
        image: sameersbn/postgresql:9.4-3
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: gitlab-db
        env:
          - name: DB_USER
            value: gitlab
          - name: DB_PASS
            value: <dbpass>
          - name: DB_NAME
            value: gitlab
      - name: gitlab-redis
        image: sameersbn/redis:latest
        volumeMounts:
        - mountPath: /var/lib/redis
          name: gitlab-redis
      volumes:
      - name: gitlab-redis
        awsElasticBlockStore:
          volumeID: aws://eu-central-1b/vol-dab9f238
          fsType: ext4
      - name: gitlab-db
        awsElasticBlockStore:
          volumeID: aws://eu-central-1b/vol-67665e85
          fsType: ext4
      - name: gitlab-data
        awsElasticBlockStore:
          volumeID: aws://eu-central-1b/vol-b2e2bf50
          fsType: ext4
